# Ejercicio 4

Del anterior problema en PYTHON y WEKA realice un árbol de decisión basado en entropía, compare los resultados, esto debe repetirse al menos 10 splits y comparar las matrices de confusión y obtener la confiabilidad. Se recomienda comparar media y mediana de los resultados.

In [108]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import tree

Realizando el arbol de desioion

In [109]:
clasificador= tree.DecisionTreeClassifier()
data= pd.read_csv("diabetes.csv", sep=",", header=[0])
X = data.iloc[:, :-1].values
Y = data.iloc[:, 9].values 
from sklearn.preprocessing import LabelEncoder
label_encoder_y = LabelEncoder()
Y = label_encoder_y.fit_transform(Y)
clasificacion=clasificador.fit(X, Y)

In [110]:
from sklearn.model_selection import StratifiedShuffleSplit
cv = StratifiedShuffleSplit(n_splits=10, test_size=0.50, random_state=0)
iteraciones = cv.split(X,Y)
from sklearn.tree import DecisionTreeClassifier
clasificador = DecisionTreeClassifier()
matrices=[[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]]]
confiabilidad=np.zeros(10)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
for indice, (train_indice, test_indice) in enumerate(iteraciones):
    print("-----")
    print(indice)
    clasificador.fit(X[train_indice],Y[train_indice])
    y_obtenido = clasificador.predict(X[test_indice])
    print(Y[test_indice])
    print(y_obtenido)
    print("")
    print("Matriz de Confusión")
    print(confusion_matrix(y_obtenido,Y[test_indice]))
    print("Precisión")
    print(precision_score(y_obtenido,Y[test_indice]),"%")
    matrices[indice]=confusion_matrix(y_obtenido,Y[test_indice])
    confiabilidad[indice]=precision_score(y_obtenido,Y[test_indice])
    

-----
0
[0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0
 1 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0
 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0
 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 1 1 0 0
 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1
 0 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0
 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 0 0 0 0 0 1 1 1 0 1 0]
[0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 1
 0 1 1 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1

Comparando resultados:

In [111]:
for i in range(10):
    print("Split: ",i)
    print("Matriz de Confusión")
    print(matrices[i])
    print("Precisión")
    print(confiabilidad[i],"%")
    print("")
    

Split:  0
Matriz de Confusión
[[213  70]
 [ 37  64]]
Precisión
0.47761194029850745 %

Split:  1
Matriz de Confusión
[[187  65]
 [ 63  69]]
Precisión
0.5149253731343284 %

Split:  2
Matriz de Confusión
[[180  49]
 [ 70  85]]
Precisión
0.6343283582089553 %

Split:  3
Matriz de Confusión
[[192  66]
 [ 58  68]]
Precisión
0.5074626865671642 %

Split:  4
Matriz de Confusión
[[180  37]
 [ 70  97]]
Precisión
0.7238805970149254 %

Split:  5
Matriz de Confusión
[[193  67]
 [ 57  67]]
Precisión
0.5 %

Split:  6
Matriz de Confusión
[[191  55]
 [ 59  79]]
Precisión
0.5895522388059702 %

Split:  7
Matriz de Confusión
[[197  66]
 [ 53  68]]
Precisión
0.5074626865671642 %

Split:  8
Matriz de Confusión
[[201  68]
 [ 49  66]]
Precisión
0.4925373134328358 %

Split:  9
Matriz de Confusión
[[201  53]
 [ 49  81]]
Precisión
0.6044776119402985 %



Media y mediana de los resultados:

In [114]:
print("Media de Matrices de confusion  :")
print(np.mean(matrices,axis=0))
print("Mediana de Matrices de confusion:")
print(np.median(matrices,axis=0))
print()
print("Media de Presicion  :",np.mean(confiabilidad))
print("Mediana de Presicion:",np.median(confiabilidad))

Media de Matrices de confusion  :
[[193.5  59.6]
 [ 56.5  74.4]]
Mediana de Matrices de confusion:
[[192.5  65.5]
 [ 57.5  68.5]]

Media de Presicion  : 0.5552238805970149
Mediana de Presicion: 0.5111940298507462
